name = "kiffane"
type = "javascript"
account_id = "55d8c232feb1745212cea0c8d83975b8"
workers_dev = true
compatibility_date = "2024-12-16"

[env.production]
vars = { RESEND_API_KEY = "re_BLFGpd2i_K4gPDJW3g6g8GWWZN3cdioSu", ZOHO_EMAIL = "hello@kiffane.com" }
